name: Deploy Web FTP 

on:
  push:
    branches:
      - testeeee
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install packages with NPM
        run: npm install
      - name: Build for production
        run: npm run build
      - name: Copy package.json to dist/app-corretora
        run: cp package.json dist/app-corretora
      - name: Upload artifacts to be used in next job
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist/app-corretora # Uploads everything from the current directory

  ftp-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts created at previous job
        if: success()
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
          path: ./
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          server-dir: public_html/
          dangerous-clean-slate: true # optional
